### ISSUE TITLE
Unknown extension ".c" for file

### ISSUE THREAD

**Issue by chlin501** [openwar/openwar#3]
This is a minor issue. It's just when building with cmake, it complains `Unknown extension ".c" for file`. Adding `ENABLE_LANGUAGE(C)` fixes the problem. 

BTW, is there any todo list or something like jira, bug report, etc.? Perhaps I can help fixing some simple issues.

**Comment by nikodil** [comment]
I'm just setting up forum.openwar.org and there's a Development section for things like user bug reporting and high-level planning. If you're willing to help out, that would be great!

**Comment by nikodil** [comment]
Add C to project languages in CMakeLists.txt in 310b5a06dcb0f75cc3529aee171b25b99fe7dff2.
