### ISSUE TITLE
Segmentation fault due to resource Map/Practice.png can't be loaded. 

### ISSUE THREAD

**Issue by chlin501** [openwar/openwar#4]
With most recent code (`4088d481e2db5f912c0d670122e70ecef1aedd15`) in origin/master, executing openwar throws Segmentation fault. After checking the code, I find that the issue basically coming from `Resource.cpp` can't load the image `Maps/Practice.png` because of the path dislocation. 

The binary `openwar` is produced under `Build-CMake` folder but the resource path obtained through `path()` function in Resource.cpp` is `Maps/Practice.png`. Create symbolic link can fix this problem, but it may be safer to have a uniform way to in accessing the resource from context root. I can work on this but perhaps other better approaches exist.

**Comment by nikodil** [comment]
It handled launching with absolute paths but not with "./openwar". I've added a fix in 1cbb802c4e2897b840cfe42d4ae793796d823b71.
